import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  stateScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F7FC",
  },
  content: {
    width: "100%",
    maxWidth: 1500,
    alignSelf: "center",
    paddingTop: 22,
    paddingBottom: 48,
  },
  contentMobile: {
    paddingTop: 14,
  },
  backButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 18,
    borderRadius: 12,
    backgroundColor: "#EAF3FF",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: "#1D4ED8",
    fontSize: 14,
    fontWeight: "800",
  },
  hero: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 24,
    marginBottom: 24,
  },
  heroMobile: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 18,
  },
  heroCopy: {
    flex: 1,
  },
  eyebrow: {
    color: "#2563EB",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1,
    marginBottom: 7,
  },
  title: {
    color: "#0F172A",
    fontSize: 36,
    lineHeight: 43,
    fontWeight: "900",
  },
  titleMobile: {
    fontSize: 29,
    lineHeight: 36,
  },
  description: {
    maxWidth: 740,
    color: "#64748B",
    fontSize: 15,
    lineHeight: 23,
    marginTop: 8,
  },
  primaryButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    backgroundColor: "#176BDE",
    paddingHorizontal: 20,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  fullWidthButton: {
    width: "100%",
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  message: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 13,
    marginBottom: 16,
  },
  errorMessage: {
    borderColor: "#FECACA",
    backgroundColor: "#FEF2F2",
  },
  errorMessageText: {
    flex: 1,
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "700",
  },
  successMessage: {
    borderColor: "#A7F3D0",
    backgroundColor: "#ECFDF5",
  },
  successMessageText: {
    flex: 1,
    color: "#047857",
    fontSize: 13,
    fontWeight: "700",
  },
  panel: {
    width: "100%",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 24,
    marginBottom: 18,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 22,
    elevation: 3,
  },
  formPanel: {
    padding: 28,
  },
  panelHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 18,
    marginBottom: 22,
  },
  panelTitle: {
    color: "#0F172A",
    fontSize: 21,
    fontWeight: "900",
  },
  panelDescription: {
    color: "#64748B",
    fontSize: 13,
    marginTop: 5,
  },
  formStepBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  formStepBadgeText: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "800",
  },
  resultBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  resultBadgeText: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "800",
  },
  sectionTitle: {
    color: "#0F172A",
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 17,
  },
  field: {
    marginBottom: 20,
  },
  fieldsRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 20,
  },
  fieldsRowMobile: {
    flexDirection: "column",
  },
  rowField: {
    flex: 1,
    minWidth: 0,
  },
  fieldLabel: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 8,
  },
  input: {
    width: "100%",
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#F8FAFC",
    color: "#0F172A",
    fontSize: 14,
    paddingHorizontal: 15,
    outlineWidth: 0,
  },
  inputDisabled: {
    color: "#94A3B8",
    backgroundColor: "#F1F5F9",
  },
  textArea: {
    minHeight: 106,
    paddingTop: 14,
    paddingBottom: 14,
  },
  segmentedControl: {
    minHeight: 50,
    flexDirection: "row",
    borderRadius: 14,
    backgroundColor: "#F1F5F9",
    padding: 4,
  },
  segment: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    paddingHorizontal: 12,
  },
  segmentActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  segmentText: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "800",
  },
  segmentTextActive: {
    color: "#176BDE",
  },
  switchesRow: {
    flexDirection: "row",
    gap: 14,
  },
  switchesRowMobile: {
    flexDirection: "column",
  },
  switchOption: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    padding: 15,
  },
  switchTrack: {
    width: 42,
    height: 24,
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#CBD5E1",
    paddingHorizontal: 3,
  },
  switchTrackActive: {
    backgroundColor: "#176BDE",
  },
  switchThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#FFFFFF",
  },
  switchThumbActive: {
    alignSelf: "flex-end",
  },
  switchCopy: {
    flex: 1,
    minWidth: 0,
  },
  switchLabel: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "800",
  },
  switchDescription: {
    color: "#64748B",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  divider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginVertical: 26,
  },
  allScopeOption: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#F8FBFF",
    padding: 16,
  },
  allScopeIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "#EAF3FF",
  },
  selectionGroup: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    padding: 16,
    marginTop: 16,
  },
  selectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 11,
  },
  selectionTitle: {
    color: "#334155",
    fontSize: 14,
    fontWeight: "900",
  },
  selectionCount: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "800",
  },
  selectionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
  },
  selectionOption: {
    width: "49%",
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  selectionOptionMobile: {
    width: "100%",
  },
  selectionOptionSelected: {
    borderColor: "#93C5FD",
    backgroundColor: "#EFF6FF",
  },
  selectionCheckbox: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
  },
  selectionCheckboxSelected: {
    borderColor: "#176BDE",
    backgroundColor: "#176BDE",
  },
  selectionOptionText: {
    flex: 1,
    color: "#475569",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  selectionOptionTextSelected: {
    color: "#1E3A8A",
  },
  inlineLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginTop: 18,
  },
  inlineLoadingText: {
    color: "#64748B",
    fontSize: 13,
  },
  formActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 28,
  },
  formActionsMobile: {
    flexDirection: "column-reverse",
  },
  actionButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 14,
    paddingHorizontal: 19,
  },
  secondaryButton: {
    backgroundColor: "#F1F5F9",
  },
  secondaryButtonText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "800",
  },
  filtersGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  filtersGridMobile: {
    flexDirection: "column",
  },
  filterField: {
    width: "32%",
    minWidth: 220,
  },
  filterFieldMobile: {
    width: "100%",
    minWidth: 0,
  },
  selectWrapper: {
    minHeight: 50,
    overflow: "hidden",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#F8FAFC",
  },
  picker: {
    width: "100%",
    minHeight: 50,
    borderWidth: 0,
    color: "#0F172A",
    backgroundColor: "transparent",
  },
  filterActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 20,
  },
  filterActionsMobile: {
    flexDirection: "column-reverse",
  },
  promotionsList: {
    gap: 14,
  },
  promotionCard: {
    width: "100%",
    flexDirection: "row",
    gap: 24,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 22,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 18,
    elevation: 2,
  },
  promotionCardMobile: {
    flexDirection: "column",
    gap: 18,
    padding: 18,
  },
  promotionMain: {
    flex: 1,
    minWidth: 0,
  },
  promotionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginBottom: 10,
  },
  promotionId: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "700",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 11,
    fontWeight: "900",
  },
  status_aktywna: {
    backgroundColor: "#ECFDF5",
  },
  status_zaplanowana: {
    backgroundColor: "#EFF6FF",
  },
  status_wygasla: {
    backgroundColor: "#F1F5F9",
  },
  status_wylaczona: {
    backgroundColor: "#FEF2F2",
  },
  statusDot_aktywna: {
    backgroundColor: "#10B981",
  },
  statusDot_zaplanowana: {
    backgroundColor: "#3B82F6",
  },
  statusDot_wygasla: {
    backgroundColor: "#94A3B8",
  },
  statusDot_wylaczona: {
    backgroundColor: "#EF4444",
  },
  statusText_aktywna: {
    color: "#047857",
  },
  statusText_zaplanowana: {
    color: "#1D4ED8",
  },
  statusText_wygasla: {
    color: "#64748B",
  },
  statusText_wylaczona: {
    color: "#B91C1C",
  },
  promotionName: {
    color: "#0F172A",
    fontSize: 19,
    lineHeight: 25,
    fontWeight: "900",
  },
  promotionDescription: {
    maxWidth: 720,
    color: "#64748B",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  scopeList: {
    gap: 7,
    marginTop: 16,
  },
  scopeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  scopeText: {
    flex: 1,
    color: "#475569",
    fontSize: 13,
    fontWeight: "600",
  },
  promotionDetails: {
    width: 430,
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    borderLeftWidth: 1,
    borderLeftColor: "#E2E8F0",
    paddingLeft: 24,
  },
  promotionDetailsMobile: {
    width: "100%",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 14,
    borderLeftWidth: 0,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    paddingLeft: 0,
    paddingTop: 17,
  },
  discountValue: {
    minWidth: 92,
  },
  discountValueText: {
    color: "#176BDE",
    fontSize: 24,
    fontWeight: "900",
  },
  discountType: {
    color: "#64748B",
    fontSize: 11,
    marginTop: 3,
  },
  dateBlock: {
    flex: 1,
    minWidth: 120,
  },
  dateLabel: {
    color: "#94A3B8",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  dateLabelEnd: {
    marginTop: 7,
  },
  dateValue: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  promotionActions: {
    minWidth: 92,
    gap: 8,
  },
  togglePromotionButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 13,
  },
  disablePromotionButton: {
    borderColor: "#FECACA",
    backgroundColor: "#FFF7F7",
  },
  enablePromotionButton: {
    borderColor: "#A7F3D0",
    backgroundColor: "#F0FDF4",
  },
  expirePromotionButton: {
    borderColor: "#FDE68A",
    backgroundColor: "#FFFBEB",
  },
  editPromotionButton: {
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
  },
  editPromotionButtonText: {
    color: "#1D4ED8",
  },
  expirePromotionButtonText: {
    color: "#B45309",
  },
  togglePromotionButtonText: {
    fontSize: 12,
    fontWeight: "900",
  },
  disablePromotionButtonText: {
    color: "#B91C1C",
  },
  enablePromotionButtonText: {
    color: "#047857",
  },
  expireModalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.52)",
    padding: 18,
  },
  expireModalCard: {
    width: "100%",
    maxWidth: 440,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#FDE68A",
    backgroundColor: "#FFFFFF",
    padding: 24,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.2,
    shadowRadius: 28,
    elevation: 8,
  },
  expireModalIcon: {
    width: 54,
    height: 54,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#FFFBEB",
    marginBottom: 18,
  },
  expireModalTitle: {
    color: "#0F172A",
    fontSize: 21,
    fontWeight: "900",
  },
  expireModalDescription: {
    color: "#64748B",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 9,
  },
  expireModalPromotionName: {
    color: "#334155",
    fontWeight: "900",
  },
  expireModalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 24,
  },
  expireModalActionsMobile: {
    flexDirection: "column-reverse",
  },
  expireModalButton: {
    minHeight: 48,
    flexGrow: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 14,
    paddingHorizontal: 18,
  },
  expireModalButtonMobile: {
    width: "100%",
    flexGrow: 0,
  },
  expireModalCancelButton: {
    backgroundColor: "#F1F5F9",
  },
  expireModalCancelButtonText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "800",
  },
  expireModalConfirmButton: {
    backgroundColor: "#D97706",
  },
  expireModalConfirmButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  emptyState: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 28,
  },
  emptyStateIcon: {
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#EAF3FF",
    marginBottom: 14,
  },
  emptyStateTitle: {
    color: "#0F172A",
    fontSize: 18,
    fontWeight: "900",
  },
  emptyStateText: {
    color: "#64748B",
    fontSize: 13,
    textAlign: "center",
    marginTop: 7,
  },
  pagination: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    marginTop: 22,
  },
  paginationMobile: {
    justifyContent: "space-between",
    gap: 8,
  },
  paginationButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 13,
  },
  paginationButtonDisabled: {
    opacity: 0.38,
  },
  paginationButtonText: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "800",
  },
  paginationText: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "800",
  },
});

export default styles;
