import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  stateScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F8FF",
  },
  content: {
    width: "100%",
    maxWidth: 1080,
    alignSelf: "center",
    marginTop: 28,
  },
  backButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 18,
    borderRadius: 12,
    backgroundColor: "#EAF3FF",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: "#1D4ED8",
    fontSize: 14,
    fontWeight: "800",
  },
  header: {
    marginBottom: 22,
  },
  eyebrow: {
    color: "#2563EB",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1,
    marginBottom: 7,
  },
  title: {
    color: "#0F172A",
    fontSize: 32,
    lineHeight: 40,
    fontWeight: "900",
  },
  description: {
    maxWidth: 720,
    color: "#64748B",
    fontSize: 15,
    lineHeight: 23,
    marginTop: 8,
  },
  formCard: {
    width: "100%",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 30,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 28,
    elevation: 8,
  },
  sectionTitle: {
    color: "#0F172A",
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 18,
  },
  sectionDescription: {
    color: "#64748B",
    fontSize: 13,
    marginTop: -10,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginVertical: 28,
  },
  sectionHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
    marginBottom: 18,
  },
  field: {
    marginBottom: 22,
  },
  fieldsRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 22,
  },
  rowField: {
    flex: 1,
    minWidth: 0,
  },
  fieldLabel: {
    color: "#0F172A",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 9,
  },
  input: {
    width: "100%",
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#F8FAFC",
    color: "#0F172A",
    fontSize: 15,
    paddingHorizontal: 16,
    outlineWidth: 0,
  },
  textArea: {
    minHeight: 120,
    paddingTop: 14,
    paddingBottom: 14,
  },
  selectWrapper: {
    minHeight: 50,
    overflow: "hidden",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#F8FAFC",
  },
  picker: {
    width: "100%",
    minHeight: 50,
    borderWidth: 0,
    color: "#0F172A",
    backgroundColor: "transparent",
  },
  imagePicker: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#93C5FD",
    backgroundColor: "#F8FBFF",
    padding: 24,
  },
  imagePickerIcon: {
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: "#EAF3FF",
    marginBottom: 12,
  },
  imagePickerTitle: {
    color: "#1E3A8A",
    fontSize: 15,
    fontWeight: "800",
  },
  imagePickerDescription: {
    color: "#64748B",
    fontSize: 13,
    marginTop: 5,
    textAlign: "center",
  },
  imagesPreview: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 16,
  },
  imagePreview: {
    position: "relative",
    width: 112,
    height: 92,
    overflow: "hidden",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DCE6F3",
    backgroundColor: "#F1F5F9",
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  removeImageButton: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "rgba(15, 23, 42, 0.78)",
  },
  addSpecificationButton: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 14,
  },
  addSpecificationText: {
    color: "#1D4ED8",
    fontSize: 13,
    fontWeight: "800",
  },
  specificationCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    padding: 18,
    marginBottom: 14,
  },
  specificationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 13,
  },
  specificationTitle: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "800",
  },
  removeSpecificationButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FECACA",
    backgroundColor: "#FFF7F7",
  },
  specificationFields: {
    flexDirection: "row",
    gap: 12,
  },
  specificationNameInput: {
    flex: 1,
  },
  specificationDescriptionInput: {
    flex: 1.5,
  },
  specificationIconInput: {
    width: 120,
  },
  errorText: {
    color: "#DC2626",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 10,
  },
  formActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 28,
  },
  actionButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 14,
    paddingHorizontal: 20,
  },
  cancelButton: {
    backgroundColor: "#F1F5F9",
  },
  cancelButtonText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "800",
  },
  submitButton: {
    backgroundColor: "#176BDE",
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
});

export default styles;
