import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F8FF",
  },
  headerShell: {
    width: "100%",
    backgroundColor: "#F4F8FF",
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 8,
    position: "relative",
    zIndex: 50,
  },
  mobileHeaderShell: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 6,
  },
  headerInner: {
    width: "100%",
    maxWidth: 1440,
    alignSelf: "center",
  },
  mobileTopBar: {
    width: "100%",
    height: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#E5ECF5",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
  },
  backButton: {
    minWidth: 76,
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 12,
    backgroundColor: "#EEF6FF",
    paddingHorizontal: 10,
  },
  backButtonText: {
    color: "#1D4ED8",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
  },
  mobileTopBarTitle: {
    color: "#0F172A",
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "800",
  },
  mobileTopBarSpacer: {
    width: 76,
  },
  scrollView: {
    flex: 1,
    backgroundColor: "#F4F8FF",
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: "center",
    paddingHorizontal: 34,
    paddingTop: 18,
    paddingBottom: 46,
  },
  mobileScrollContent: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 28,
  },
  page: {
    width: "100%",
    maxWidth: 1080,
    position: "relative",
  },
  backgroundDecorations: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  backgroundOrbOne: {
    position: "absolute",
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "rgba(147,197,253,0.16)",
    left: -185,
    top: 150,
  },
  backgroundOrbTwo: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "rgba(191,219,254,0.22)",
    right: -150,
    bottom: -40,
  },
  hero: {
    minHeight: 240,
    borderRadius: 34,
    overflow: "hidden",
    paddingHorizontal: 58,
    paddingVertical: 40,
  },
  mobileHero: {
    minHeight: 240,
    borderRadius: 26,
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    maxWidth: 590,
  },
  heroWatermark: {
    position: "absolute",
    right: 54,
    bottom: -42,
    transform: [{ rotate: "-7deg" }],
  },
  heroGlowTop: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "rgba(255,255,255,0.10)",
    right: -65,
    top: -95,
  },
  heroGlowBottom: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255,255,255,0.08)",
    right: 150,
    bottom: -120,
  },
  heroLabel: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(219,234,254,0.42)",
    backgroundColor: "rgba(30,64,175,0.24)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 17,
  },
  heroLabelText: {
    color: "#EFF6FF",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 0.9,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 42,
    lineHeight: 50,
    fontWeight: "900",
    letterSpacing: -0.8,
    marginBottom: 8,
  },
  mobileHeroTitle: {
    fontSize: 32,
    lineHeight: 39,
  },
  heroSubtitle: {
    color: "#DBEAFE",
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500",
  },
  accountLinks: {
    flexDirection: "row",
    gap: 14,
    marginHorizontal: 38,
    marginTop: 22,
    position: "relative",
    zIndex: 3,
  },
  mobileAccountLinks: {
    flexDirection: "column",
    marginHorizontal: 8,
    marginTop: 14,
  },
  accountLinkButton: {
    flex: 1,
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 18,
  },
  accountLinkText: {
    flex: 1,
    color: "#0F172A",
    fontSize: 15,
    fontWeight: "800",
  },
  accountCard: {
    width: "auto",
    minHeight: 440,
    marginHorizontal: 38,
    marginTop: 22,
    paddingHorizontal: 46,
    paddingTop: 38,
    paddingBottom: 42,
    borderRadius: 30,
    backgroundColor: "#FFFFFF",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 22 },
    shadowOpacity: 0.11,
    shadowRadius: 38,
    elevation: 18,
    position: "relative",
    zIndex: 3,
  },
  mobileAccountCard: {
    marginHorizontal: 8,
    marginTop: 14,
    paddingHorizontal: 18,
    paddingTop: 26,
    paddingBottom: 24,
    borderRadius: 23,
  },
  profileHeader: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
  },
  mobileProfileHeader: {
    flexDirection: "column",
    alignItems: "center",
  },
  avatar: {
    width: 86,
    height: 86,
    borderRadius: 27,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#EEF6FF",
    borderWidth: 1,
    borderColor: "#DBEAFE",
    marginRight: 20,
  },
  identity: {
    flex: 1,
    minWidth: 0,
  },
  mobileIdentity: {
    width: "100%",
    alignItems: "center",
    marginTop: 14,
  },
  profileActions: {
    flexDirection: "row",
    gap: 8,
    marginLeft: 16,
  },
  mobileProfileActions: {
    marginLeft: 0,
    marginTop: 14,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: "800",
  },
  editButton: {
    backgroundColor: "#EFF6FF",
  },
  editButtonText: {
    color: "#1D4ED8",
  },
  saveButton: {
    backgroundColor: "#2563EB",
  },
  saveButtonText: {
    color: "#FFFFFF",
  },
  cancelButton: {
    backgroundColor: "#F1F5F9",
  },
  cancelButtonText: {
    color: "#475569",
  },
  name: {
    color: "#071536",
    fontSize: 27,
    lineHeight: 34,
    fontWeight: "900",
    marginBottom: 4,
  },
  mobileName: {
    fontSize: 23,
    lineHeight: 30,
    textAlign: "center",
  },
  email: {
    color: "#7B88A4",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "500",
  },
  accountBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    backgroundColor: "#F0FDF4",
    paddingHorizontal: 13,
    paddingVertical: 8,
    marginLeft: 20,
  },
  mobileAccountBadge: {
    marginLeft: 0,
    marginTop: 16,
  },
  accountBadgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#22C55E",
    marginRight: 7,
  },
  accountBadgeText: {
    color: "#15803D",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "#E8EEF7",
    marginTop: 28,
    marginBottom: 28,
  },
  sectionHeading: {
    marginBottom: 18,
  },
  sectionEyebrow: {
    color: "#2563EB",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 5,
  },
  sectionTitle: {
    color: "#0F172A",
    fontSize: 21,
    lineHeight: 28,
    fontWeight: "800",
  },
  detailsGrid: {
    width: "100%",
    flexDirection: "row",
    gap: 14,
    marginBottom: 16,
  },
  mobileDetailsGrid: {
    flexDirection: "column",
  },
  detailCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 92,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FBFDFF",
    paddingHorizontal: 17,
    paddingVertical: 15,
  },
  detailIcon: {
    width: 43,
    height: 43,
    borderRadius: 13,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#EEF6FF",
    marginRight: 13,
  },
  detailContent: {
    flex: 1,
    minWidth: 0,
  },
  detailLabel: {
    color: "#94A3B8",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
    marginBottom: 3,
  },
  detailValue: {
    color: "#0F172A",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "700",
  },
  editableDetailValue: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    outlineWidth: 0,
  },
  emailChangeButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 9,
    borderRadius: 10,
    backgroundColor: "#EEF6FF",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  emailChangeButtonPressed: {
    opacity: 0.7,
  },
  emailChangeButtonText: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "800",
  },
  roleValue: {
    textTransform: "capitalize",
  },
  securityCard: {
    width: "100%",
    minHeight: 94,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 20,
  },
  mobileSecurityCard: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 16,
  },
  securityInfo: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  mobileSecurityInfo: {
    width: "100%",
  },
  securityIcon: {
    width: 48,
    height: 48,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    marginRight: 14,
  },
  securityIconEnabled: {
    backgroundColor: "#DCFCE7",
  },
  securityText: {
    flex: 1,
    minWidth: 0,
  },
  securityTitle: {
    color: "#0F172A",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "800",
    marginBottom: 2,
  },
  securityDescription: {
    color: "#7B88A4",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
  },
  twoFactorBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  twoFactorBadgeEnabled: {
    backgroundColor: "#DCFCE7",
  },
  twoFactorBadgeDisabled: {
    backgroundColor: "#E2E8F0",
  },
  twoFactorDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    marginRight: 7,
  },
  twoFactorDotEnabled: {
    backgroundColor: "#22C55E",
  },
  twoFactorDotDisabled: {
    backgroundColor: "#94A3B8",
  },
  twoFactorText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  twoFactorTextEnabled: {
    color: "#15803D",
  },
  twoFactorTextDisabled: {
    color: "#475569",
  },
  modalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.48)",
    paddingHorizontal: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    alignItems: "center",
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 28,
    paddingVertical: 30,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 30,
    elevation: 18,
  },
  modalIcon: {
    width: 58,
    height: 58,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#FEF2F2",
    marginBottom: 16,
  },
  modalTitle: {
    color: "#0F172A",
    fontSize: 20,
    lineHeight: 27,
    fontWeight: "800",
    textAlign: "center",
  },
  modalActions: {
    width: "100%",
    flexDirection: "row",
    gap: 12,
    marginTop: 24,
  },
  modalButton: {
    flex: 1,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
  },
  modalCancelButton: {
    backgroundColor: "#F1F5F9",
  },
  modalConfirmButton: {
    backgroundColor: "#DC2626",
  },
  modalCancelButtonText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "800",
  },
  modalConfirmButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  stateScreen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F4F8FF",
    paddingHorizontal: 20,
  },
  stateCard: {
    width: "100%",
    maxWidth: 520,
    minHeight: 220,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 28,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 30,
    paddingVertical: 36,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.09,
    shadowRadius: 30,
    elevation: 14,
  },
  stateIcon: {
    width: 60,
    height: 60,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#EEF6FF",
    marginBottom: 17,
  },
  stateTitle: {
    color: "#071536",
    fontSize: 20,
    lineHeight: 27,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 16,
  },
  stateDescription: {
    color: "#7B88A4",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 8,
  },
  errorStateIcon: {
    backgroundColor: "#FEF2F2",
  },
  errorStateText: {
    color: "#991B1B",
    marginTop: 0,
  },
});

export default styles;
