import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  stateScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F8FF",
  },
  content: {
    width: "100%",
    maxWidth: 920,
    alignSelf: "center",
    marginTop: 28,
  },
  backButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 18,
    borderRadius: 12,
    backgroundColor: "#EAF3FF",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: "#1D4ED8",
    fontSize: 14,
    fontWeight: "800",
  },
  header: {
    marginBottom: 22,
  },
  eyebrow: {
    color: "#2563EB",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1,
    marginBottom: 7,
  },
  title: {
    color: "#0F172A",
    fontSize: 32,
    lineHeight: 40,
    fontWeight: "900",
  },
  description: {
    maxWidth: 650,
    color: "#64748B",
    fontSize: 15,
    lineHeight: 23,
    marginTop: 8,
  },
  categoryIdBadge: {
    alignSelf: "flex-start",
    marginTop: 14,
    borderRadius: 999,
    backgroundColor: "#EAF3FF",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  categoryIdText: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "800",
  },
  formCard: {
    width: "100%",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 30,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 28,
    elevation: 8,
  },
  field: {
    marginBottom: 24,
  },
  fieldLabel: {
    color: "#0F172A",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 9,
  },
  input: {
    width: "100%",
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#F8FAFC",
    color: "#0F172A",
    fontSize: 15,
    paddingHorizontal: 16,
    outlineWidth: 0,
  },
  imagePicker: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#93C5FD",
    backgroundColor: "#F8FBFF",
    padding: 24,
  },
  imagePickerIcon: {
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: "#EAF3FF",
    marginBottom: 12,
  },
  imagePickerTitle: {
    color: "#1E3A8A",
    fontSize: 15,
    fontWeight: "800",
  },
  imagePickerDescription: {
    color: "#64748B",
    fontSize: 13,
    marginTop: 5,
    textAlign: "center",
  },
  formActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 4,
  },
  actionButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 14,
    paddingHorizontal: 20,
  },
  cancelButton: {
    backgroundColor: "#F1F5F9",
  },
  cancelButtonText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "800",
  },
  submitButton: {
    backgroundColor: "#176BDE",
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
});

export default styles;
